
version: '3'

services:
  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100

  # promtail:
  #   image: grafana/promtail:latest
  #   # command: -config.file=/etc/promtail/config.yml
  #   # volumes:
  #   #   - /var/log:/var/log

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
