version: '3'

services:
  app:
    build: .
    container_name: freeradius
    command: radiusd -xx -f
    ports:
      - 1812:1812/udp
      - 1813:1813
      - 18120:18120
    volumes:
      - ${CONFIG_PATH:-./config}/clients.conf:/etc/raddb/clients.conf
      - ${CONFIG_PATH:-./config}/users:/etc/raddb/users

  test:
    build: .
    command: "radtest testing password app 0 SECRET"
    depends_on:
      - app
