version: '3'

services:
  artifactory:
    image: atlassian/bitbucket-server:latest
    ports:
      - ${HOST_PORT:-7990}:7990
    volumes:
      - ${DATA_PATH:-./data/bitbucket}:/var/atlassian/application-data/bitbucket
