version: '3'

services:
  oracle:
    image: wnameless/oracle-xe-11g-r2:latest
    container_name: oracle
    environment:
      ORACLE_ALLOW_REMOTE: 'false'
    ports:
      - ${HOST_PORT:-1521}:1521

  client:
    build:
      dockerfile: Dockerfile.client
      context: .
    depends_on:
      - oracle
