# TeamCity Docker
# https://hub.docker.com/r/jetbrains/teamcity-server/

version: '3'

services:
  server:
    image: jetbrains/teamcity-server
    container_name: teamcity-server
    restart: always
    ports:
      - ${HOST_PORT:-8111}:8111
    volumes:
      - ${DATA_PATH:-./data}:/data/teamcity_server/datadir
      - ${LOGS_PATH:-./logs}:/opt/teamcity/logs
