version: '3'

services:
  server:
    image: jetbrains/teamcity-server
    ports:
      - ${HOST_PORT:-8111}:8111
    volumes:
      - ${DATA_PATH:-./data}:/data/teamcity_server/datadir
      - ${LOGS_PATH:-./logs}:/opt/teamcity/logs
