version: '3'

services:
  # db:
  #   image: mariadb:latest
  #   volumes:
  #     - ${DB_DATA_PATH:-./data/mariadb}:/var/lib/mysql

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    # environment:
    #   MYSQL_DATABASE: ''
    #   MYSQL_USER: ''
    #   MYSQL_PASSWORD: ''
    #   MYSQL_HOST: ''
    #   POSTGRES_DB: ''
    #   POSTGRES_USER: ''
    #   POSTGRES_PASSWORD: ''
    #   POSTGRES_HOST: ''
    #   NEXTCLOUD_ADMIN_USER: admin
    #   NEXTCLOUD_ADMIN_PASSWORD: 1234
    #   NEXTCLOUD_DATA_DIR: /var/www/html/data
    #   NEXTCLOUD_TABLE_PREFIX: ''
    ports:
      - ${HOST_PORT:-8080}:80
    volumes:
      - ${DATA_PATH:-./data/nextcloud}:/var/www/html
      # - /var/www/html Main folder, needed for updating
      # - /var/www/html/custom_apps installed / modified apps
      # - /var/www/html/config local configuration
      # - /var/www/html/data the actual data of your Nextcloud
      # - /var/www/html/themes/<YOUR_CUSTOM_THEME> theming/branding
