# Hashicorp Consul Docker
# https://hub.docker.com/_/consul/

version: '3'

services:
  server:
    image: consul
    container_name: consul
    environment:
      CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true}'
    ports:
      - ${HOST_PORT:-8500}:8500
    volumes:
      - ${CONFIG_PATH:-./data/consul/config}:/consul/config
      - ${DATA_PATH:-./data/consul/data}:/consul/data
