version: '3'

services:
  artifactory:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - ${HOST_PORT:-8080}:8080
      - ${HOST_PORT2:-50000}:50000
    volumes:
      - ${DATA_PATH:-./data/jenkins_home}:/var/jenkins_home
