version: "3"

services:
  server:
    image: vault
    environment:
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: myroot
    cap_add:
      - IPC_LOCK
    ports:
      - 8200:8200
    # volumes:
    #   - ${FILE_PATH:-./data/vault/file}:/vault/file
    #   - ${LOGS_PATH:-./data/vault/logs}:/vault/logs
