version: '3'

services:
  server:
    image: jkarlos/git-server-docker
    ports:
      - ${HOST_PORT:-2222}:22
    volumes:
      - ${KEYS_PATH:-./keys}:/git-server/keys
      - ${REPOS_PATH:-./repos}:/git-server/repos
