# OpenLDAP Docker
# https://github.com/osixia/docker-openldap

version: '3'

services:
  app:
    image: osixia/openldap
    container_name: ldap
    # restart: always
    environment:
      LDAP_ORGANISATION: ${LDAP_ORGANISATION:-Home}
      LDAP_DOMAIN: ${LDAP_DOMAIN:-home.local}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD:-password}
    # hostname: ldap.home.local
    # network_mode: host
    # networks:
    #   - default
    volumes:
      - ${CONFIG_PATH:-./config}:/etc/ldap/slapd.d
      - ${DATABASE_PATH:-./database}:/var/lib/ldap
