version: '3'

networks:
  default:
    external:
      name: ${DOCKER_NETWORK:-default}

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD:-yes}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-""}
    networks:
      default:
        aliases:
          - ${VIRTUAL_HOST:-mysql}
    ports:
      - ${HOST_PORT:-3306}:3306
    volumes:
      - ${DATA_DIR:-./data}:/var/lib/mysql
