version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: ${DOCKER_RESTART:-no}
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST:-mysql}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD:-yes}
    ports:
      - ${HOST_PORT:-3306}:3306
    volumes:
      - ${DATA_PATH:-./data}:/var/lib/mysql
