version: '3'

services:
  ghost:
    image: ghost:1-alpine
    container_name: ghost
    # environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
    ports:
      - ${HOST_PORT:-2368}:2368
    volumes:
      - ${CONTENT_PATH:-./data/content}:/var/lib/ghost/content
