# Ghost Docker
# https://hub.docker.com/_/ghost/

version: '3'

services:
  ghost:
    image: ghost:1-alpine
    container_name: ghost
    ports:
      - ${HOST_PORT:-2368}:2368
    volumes:
      - ${CONTENT_PATH:-./data/content}:/var/lib/ghost/content
