version: '3'

services:
  web:
    image: gitlab/gitlab-ce
    restart: always
    hostname: gitlab.example.com
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com:9090'
        gitlab_rails['gitlab_shell_ssh_port'] = ${HOST_SSH_PORT:-2224}
    ports:
      - ${HOST_PORT:-9090}:9090
      - ${HOST_SSH_PORT:-2224}:22
    volumes:
      - ${DATA_DIR:-./data}/gitlab/config:/etc/gitlab
      - ${DATA_DIR:-./data}/gitlab/logs:/var/log/gitlab
      - ${DATA_DIR:-./data}/gitlab/data:/var/opt/gitlab
