version: '3'

volumes:
  # docker volume create --name postgres_data
  postgres_data:
    external: true

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: ${DOCKER_RESTART:-unless-stopped}
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-}
      VIRTUAL_HOST: ${VIRTUAL_HOST:-postgres}
    ports:
      - ${HOST_PORT:-5432}:5432
    volumes:
      # - ${DATA_PATH:-./data}:/var/lib/postgresql/data/pgdata
      - postgres_data:/var/lib/postgresql/data
      - ./certs/server.key:/var/lib/postgresql/server.key:ro
      - ./certs/server.crt:/var/lib/postgresql/server.crt:ro
      - ./certs/rootCA.key:/var/lib/postgresql/root.key:ro
      - ./certs/rootCA.crt:/var/lib/postgresql/root.crt:ro
