version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: ${DOCKER_RESTART:-no}
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST:-postgres}
    ports:
      - ${HOST_PORT:-5432}:5432
    volumes:
      - ${DATA_PATH:-./data}:/var/lib/postgresql/data/pgdata
