
version: '3'

services:
  influxdb:
    image: influxdb:alpine
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin1234
      DOCKER_INFLUXDB_INIT_ORG: my-org
      DOCKER_INFLUXDB_INIT_BUCKET: my-bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-token
    ports:
      - 8086:8086
    expose:
      - 8086
    volumes:
      - ./data:/var/lib/influxdb2
      - ./config:/etc/influxdb
