version: '3'

volumes:
  # docker volume create --name redis_data
  redis_data:
    external: true

services:
  redis:
    image: redis:latest
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST:-redis}
    ports:
      - ${HOST_PORT:-6379}:6379
    volumes:
      - redis_data:/data
